### ISSUE TITLE
RuntimeError: CUDA error: misaligned address

### ISSUE THREAD

**Issue by Fidode07** [zeyad-mansour/Lunar#109]
I get the Error everytime ...

Traceback (most recent call last):
  File "C:\Users\USERNAME\Desktop\DEVELOPMENT\PyCheat\Fn\Lunar-main\Lunar-main\lunar.py", line 74, in <module>
    main()
  File "C:\Users\USERNAME\Desktop\DEVELOPMENT\PyCheat\Fn\Lunar-main\Lunar-main\lunar.py", line 22, in main
    lunar.start()
  File "C:\Users\USERNAME\Desktop\DEVELOPMENT\PyCheat\Fn\Lunar-main\Lunar-main\lib\aimbot.py", line 168, in start
    results = self.model(frame)
  File "C:\Users\USERNAME\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USERNAME\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\USERNAME/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 539, in forward
    t.append(time_sync())
  File "C:\Users\USERNAME/.cache\torch\hub\ultralytics_yolov5_master\utils\torch_utils.py", line 100, in time_sync
    torch.cuda.synchronize()
  File "C:\Users\USERNAME\anaconda3\lib\site-packages\torch\cuda\__init__.py", line 493, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by tripathiarpan20** [comment]
Got the same issue.
@zeyad-mansour Can you please help with this? 
Thanks

**Comment by Fidode07** [comment]
My Graphicscard has a Hardware Error. I dont know what exactly is defect. But it's the reason for the Error.
