### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by MrNoxy** [zeyad-mansour/lunar#248]
Traceback (most recent call last):
  File "C:\Users\NoxyXD\Downloads\lunar-main\lunar-main\lunar.py", line 71, in <module>
    from lib.aimbot import Aimbot
  File "C:\Users\NoxyXD\Downloads\lunar-main\lunar-main\lib\aimbot.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

[https://media.discordapp.net/attachments/1088134677451255829/1096559169248698369/image.png?width=822&height=463](url)

**Comment by TonttuHomo** [comment]
pip install opencv-python
