### ISSUE TITLE
Some erors help

### ISSUE THREAD

**Issue by EmilHero** [zeyad-mansour/lunar#259]
| |
    | |    _   _ _ __   __ _ _ __
    | |   | | | | '_ \ / _` | '__|
    | |___| |_| | | | | (_| | |
    \_____/\__,_|_| |_|\__,_|_|

    (Neural Network Aimbot)
[INFO] Loading the neural network model
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\Gerila/.cache\torch\hub\master.zip
YOLOv5  2023-5-21 Python-3.10.11 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1080, 8192MiB)

Traceback (most recent call last):
  File "C:\Users\Gerila/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 49, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "C:\Users\Gerila/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 344, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "C:\Users\Gerila/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'lib\\best.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gerila/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 60, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "C:\Users\Gerila/.cache\torch\hub\ultralytics_yolov5_master\models\experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'lib\\best.pt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\lunar-main\lunar.py", line 74, in <module>
    main()
  File "C:\lunar-main\lunar.py", line 21, in main
    lunar = Aimbot(collect_data = "collect_data" in sys.argv)
  File "C:\lunar-main\lib\aimbot.py", line 65, in __init__
    self.model = torch.hub.load('ultralytics/yolov5', 'custom', path='lib/best.pt', force_reload = True)
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Gerila\AppData\Roaming\Python\Python310\site-packages\torch\hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Gerila/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\Gerila/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: [Errno 2] No such file or directory: 'lib\\best.pt'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.

C:\Users\Gerila>

**Comment by Dominikbec** [comment]
I uploaded a new exe version here:
shorturl.at/nuvD4

**Comment by EmilHero** [comment]
This file does not exist

нед, 21. мај 2023. у 02:03 Dominikbec ***@***.***> је
написао/ла:
