### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by Insomniaxs** [zeyad-mansour/lunar#277]
When I already runned setup it installed etc. than I run it it says downloading and this happens:
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\admin/.cache\torch\hub\master.zip
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\lunar-main\lunar-main\lunar.py", line 74, in <module>
    main()
  File "C:\Users\admin\Downloads\lunar-main\lunar-main\lunar.py", line 21, in main
    lunar = Aimbot(collect_data = "collect_data" in sys.argv)
  File "C:\Users\admin\Downloads\lunar-main\lunar-main\lib\aimbot.py", line 65, in __init__
    self.model = torch.hub.load('ultralytics/yolov5', 'custom', path='lib/best.pt', force_reload = True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\admin/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\admin/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "C:\Users\admin/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "C:\Users\admin/.cache\torch\hub\ultralytics_yolov5_master\utils\dataloaders.py", line 22, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

If you a fix I'll be grateful

**Comment by sweaty21msl** [comment]
hey i have the same problem luckily i have figured it out do "pip install psutil"
