### ISSUE TITLE
Issue when trying to start

### ISSUE THREAD

**Issue by Vitusc** [zeyad-mansour/Lunar#3]
[INFO]  PRESS 'F1' 
[INFO]  PRESS 'F2' 
[INFO] Recording
Traceback (most recent call last):
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\Scripts\lunar.py", line 44, in <module>
    main()
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\Scripts\lunar.py", line 26, in main
    lunar.start()
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\Scripts\lib\aimbot.py", line 120, in start
    cv2.rectangle(frame, x1y1, x2y2, [0, 0, 255], 2) #draw the bounding boxes
TypeError: function takes exactly 4 arguments (2 given)
PS C:\Users\XYZ\AppData\Local\Programs\Python\Python39\Scripts>

**Comment by zeyad-mansour** [comment]
Hey, it seems like you are using Python version 3.9.x 

Using Python 3.7.x should fix the error that you are encountering.

**Comment by Vitusc** [comment]
Yep, that's working thanks.
