### ISSUE TITLE
error pls help

### ISSUE THREAD

**Issue by slavjustslav** [zeyad-mansour/Lunar#58]
after i enter the sensitivity it show me that this is dona and then this message

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Lunar-main\lunar.py", line 71, in <module>
    from lib.aimbot import Aimbot
  File "C:\Users\Admin\Desktop\Lunar-main\lib\aimbot.py", line 10, in <module>
    import torch
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

i will be so thankful if you help me!

**Comment by zeyad-mansour** [comment]
PyTorch is trying to load a wrong version of the library since it says "The specified procedure could not be found" which means the DLL is found but some function in it is not. There may be some old DLLs in the lib directory, so you can just clean those up with `pip uninstall torch`. Then, try running `pip install -r requirements.txt` again.

**Comment by slavjustslav** [comment]
I successfully uninstalled torch but i got an error message for all the plugins when I tried the second command.

here is the message:

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
    super().__init__(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\network\download.py", line 132, in __call__
    resp = _http_get_download(self._session, link)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\network\download.py", line 115, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\network\session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 184, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 129, in unpackb
    ret = unpacker._unpack()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 671, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 671, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 625, in _unpack
    typ, n, obj = self._read_header(execute)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 468, in _read_header
    obj = self._read(n)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 376, in _read
    ret = self._buffer[i : i + n]
MemoryError
```

**Comment by slavjustslav** [comment]
it actually worked now

**Comment by Fooglezxc** [comment]
Hello pls help me have this problem: [!] Sensitivity configuration is not set
[INFO] In-game X and Y axis sensitivity should be the same
X-Axis and Y-Axis Sensitivity (from in-game settings): X-Axis 28,0%
[!] Invalid Input. Make sure to enter only the number (e.g. 6.9)
X-Axis and Y-Axis Sensitivity (from in-game settings): X-Axis 28
[!] Invalid Input. Make sure to enter only the number (e.g. 6.9)
X-Axis and Y-Axis Sensitivity (from in-game settings): x.y 28
[!] Invalid Input. Make sure to enter only the number (e.g. 6.9)
X-Axis and Y-Axis Sensitivity (from in-game settings): e.g 28
[!] Invalid Input. Make sure to enter only the number (e.g. 6.9)
X-Axis and Y-Axis Sensitivity (from in-game settings): 28.0
Targeting Sensitivity (from in-game settings): 19.6
[INFO] Your in-game targeting sensitivity must be the same as your scoping sensitivity
[INFO] Sensitivity configuration complete
Traceback (most recent call last):
  File "C:\lunar-main\lunar.py", line 71, in <module>
    from lib.aimbot import Aimbot
  File "C:\lunar-main\lib\aimbot.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
