### ISSUE TITLE
help please!

### ISSUE THREAD

**Issue by Vlynex** [zeyad-mansour/Lunar#59]
Using cache found in C:\Users\vlyne/.cache\torch\hub\ultralytics_yolov5_master
Traceback (most recent call last):
  File "C:\Users\vlyne/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 43, in _create
    device = select_device(('0' if torch.cuda.is_available() else 'cpu') if device is None else device)
  File "C:\Users\vlyne/.cache\torch\hub\ultralytics_yolov5_master\utils\torch_utils.py", line 70, in select_device
    s = f'YOLOv5 🚀 {git_describe() or date_modified()} torch {torch.__version__} '  # string
  File "C:\Users\vlyne/.cache\torch\hub\ultralytics_yolov5_master\utils\torch_utils.py", line 63, in git_describe
    return subprocess.check_output(s, shell=True, stderr=subprocess.STDOUT).decode()[:-1]
  File "C:\Users\vlyne\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Users\vlyne\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\vlyne\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\vlyne\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lunar.py", line 74, in <module>
    main()
  File "lunar.py", line 21, in main
    lunar = Aimbot(collect_data = "collect_data" in sys.argv)
  File "C:\Users\vlyne\Desktop\Lunar-main (3)\Lunar-main\lib\aimbot.py", line 65, in __init__
    self.model = torch.hub.load('ultralytics/yolov5', 'custom', path='lib/best.pt')
  File "C:\Users\vlyne\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\hub.py", line 364, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\vlyne\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\hub.py", line 393, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\vlyne/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 70, in custom
    return _create(path, autoshape=autoshape, verbose=verbose, device=device)
  File "C:\Users\vlyne/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 65, in _create
    raise Exception(s) from e
Exception: Cache may be out of date, try `force_reload=True`. See https://github.com/ultralytics/yolov5/issues/36 for help.

**Comment by zeyad-mansour** [comment]
The error is self-explanatory. If you clone now, it should be fixed.
