### ISSUE TITLE
ModuleNotFoundError: No module named 'win32.api'

### ISSUE THREAD

**Issue by 0Abstract** [zeyad-mansour/Lunar#65]
I have installed, reinstalled and wiped python off my pc twice because of this stupid issue of it not being able to find win32.api. Ive installed every package with win32 in the name. any help?

Actual Error:  Traceback (most recent call last):
  File "C:\Users\user\Music\.Lunar\lunar.py", line 71, in <module>
    from lib.aimbot import Aimbot
  File "C:\Users\user\Music\.Lunar\lib\aimbot.py", line 12, in <module>
    import win32api
  File "C:\Python39\lib\site-packages\win32api\__init__.py", line 1, in <module>
    from win32.api import *
ModuleNotFoundError: No module named 'win32.api'

**Comment by Pokemen** [comment]
Using the old version package may solve the problem

**Comment by IGmatthewbechard2** [comment]
its windows exclusive
