### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by 89054321167** [zeyad-mansour/Lunar#96]
Traceback (most recent call last):
  File "lunar.py", line 74, in <module>
    main()
  File "lunar.py", line 22, in main
    lunar.start()
  File "C:\Users\admin\Downloads\Lunar-main\lib\aimbot.py", line 177, in start
    crosshair_dist = math.dist((relative_head_X, relative_head_Y), (self.box_constant/2, self.box_constant/2))
AttributeError: module 'math' has no attribute 'dist'

**Comment by leesheedy** [comment]
fixed it?
